version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres_db
    ports:
      - "5555:5432"
    restart: always
    user: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
